# See http://about.travis-ci.org/docs/user/build-configuration/
language: scala

scala:
   - 2.12.2

branches:
  only:
    - master

jdk:
  - oraclejdk9
  - oraclejdk8

script:
  - sbt clean coverage test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
